from __future__ import annotations

from app.models import (
    ChordAnchor,
    ChordEvent,
    LyricLine,
    LyricWord,
    SongLine,
    SongLyricSegment,
    SongSection,
    SongSheetCompat,
)


def find_active_chord(chord_events: list[ChordEvent], time: float) -> ChordEvent | None:
    for ev in chord_events:
        if ev.start <= time < ev.end:
            return ev
    return None


def anchor_chords_to_words(
    lyric_words: list[LyricWord],
    chord_events: list[ChordEvent],
) -> list[ChordAnchor]:
    """Attach the chord active at each word's start time to that word."""
    anchors: list[ChordAnchor] = []
    for word in lyric_words:
        ev = find_active_chord(chord_events, word.start)
        if ev is not None and ev.chord != "N":
            anchors.append(ChordAnchor(chord=ev.chord, time=word.start, confidence=ev.confidence))
    return anchors


def lyrics_to_sections(
    lyric_lines: list[LyricLine],
    chord_events: list[ChordEvent],
) -> list[SongSection]:
    """Build SongSheet-compatible sections with chord anchors placed above words.

    Chords are emitted as separate lyric segments (badges above the text) using
    the same ``SongLyricSegment`` shape (``chord`` / ``text``) the Song Chords
    reader consumes. We do not splice chord text into the lyric strings.
    """
    sections: list[SongSection] = []
    for line_idx, line in enumerate(lyric_lines):
        segments: list[SongLyricSegment] = []
        for word in line.words:
            ev = find_active_chord(chord_events, word.start)
            chord = ev.chord if (ev is not None and ev.chord != "N") else None
            segments.append(SongLyricSegment(chord=chord, text=word.text))
        sections.append(
            SongSection(
                id=f"fs1-{line_idx}",
                title=f"Verse {line_idx + 1}",
                type="verse",
                lines=[SongLine(id=f"fs1-line-{line_idx}", segments=segments)],
            )
        )
    return sections


def build_song_sheet(
    *,
    song_id: str,
    title: str,
    lyric_lines: list[LyricLine],
    chord_events: list[ChordEvent],
    chords_used: list[str],
    key: str,
) -> SongSheetCompat:
    sections = lyrics_to_sections(lyric_lines, chord_events)
    used = list(dict.fromkeys(chords_used))
    return SongSheetCompat(
        id=song_id,
        metadata={
            "title": title,
            "composer": "Detected (unverified)",
            "periodOrOrigin": "Automatic full-song detection",
            "attribution": "AI-detected — verify before publication",
            "difficulty": "Beginner",
            "key": key if key else "C",
            "originalKey": key if key else "C",
            "timeSignature": "4/4",
            "tuning": "E A D G B E",
            "defaultCapo": 0,
            "description": "Prototype sheet automatically generated by Phase FS1. Lyrics and chords are estimated and may contain errors.",
            "isPublicDomain": False,
        },
        chordsUsed=used,
        sections=sections,
    )
